BEGIN;

INSERT INTO races (name, race_date, location) VALUES('Armory January Middle School Invitational Sponsored by NYRR', '2017-01-04', 'Armory Track');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Joe Kleinerman 10K', '2017-01-07', 'Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Millrose Games Trials', '2017-01-11', 'Armory Track');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Night at the Races', '2017-01-12', 'Armory Track');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Fred Lebow Manhattan Half', '2017-01-22', 'Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Night at the Races', '2017-01-26', 'Armory Track');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Gridiron 4M /Longest Football Throw', '2017-02-05', 'Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Millrose Games Youth Clinic','2017-02-09','Armory Track');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Millrose Games','2017-02-11','Armory Track');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Al Gordon 4M','2017-02-25','Prospect Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Night at the Races','2017-03-02','Armory Track');
INSERT INTO races (name, race_date, location) VALUES ('Armory Youth Championships Sponsored by NYRR','2017-03-04','Armory Track');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Washington Heights Salsa Blues and Shamrocks 5K','2017-03-05','Manhattan');
INSERT INTO races (name, race_date, location) VALUES ('Kids Races at the NYRR Washington Heights Salsa Blues and Shamrocks 5K','2017-03-05','Manhattan');
INSERT INTO races (name, race_date, location) VALUES ('United Airlines NYC Half','2017-03-19','Manhattan');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Times Square Youth Run at the United Airlines NYC Half','2017-03-19','Manhattan');
INSERT INTO races (name, race_date, location) VALUES ('Armory NYC Indoor Marathon Presented by NYRR','2017-03-24','Armory Track');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Central Park Spring Classic 10K','2017-03-25','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Boomers Cystic Fibrosis Run to Breathe (4M)','2017-04-01','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR 10K','2017-04-09','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Run as One (4M) Presented by JPMorgan Chase','2017-04-23','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('SHAPE Women''s Half-Marathon','2017-04-30','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Japan Run (4M)','2017-05-14','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Airbnb Brooklyn Half','2017-05-20','Brooklyn');
INSERT INTO races (name, race_date, location) VALUES ('NYRR 4M','2017-06-04','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Global Running Day','2017-06-07','Five Boroughs');
INSERT INTO races (name, race_date, location) VALUES ('NYRR New York Mini 10K','2017-06-10','Manhattan');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Queens 5K','2017-06-17','Queens');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Five-Borough Series: Queens 10K','2017-06-17','Queens');
INSERT INTO races (name, race_date, location) VALUES ('Front Runners New York LGBT Pride Run (5M)','2017-06-24','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Achilles Hope & Possibility (4M)','2017-06-25','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR 4M','2017-07-08','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('TCS New York City Marathon Long Training Run #1','2017-07-22','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR R-U-N 5K','2017-07-27','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Team Championships: Women (5M)','2017-08-05','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Team Championships: Men (5M)','2017-08-05','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('TCS New York City Marathon Long Training Run #2','2017-08-13','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR 8K','2017-08-20','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Percy Sutton Harlem 5K Run','2017-08-26','Manhattan');
INSERT INTO races (name, race_date, location) VALUES ('Percy Sutton Harlem Walk','2017-08-26','Manhattan');
INSERT INTO races (name, race_date, location) VALUES ('New Balance 5th Avenue Mile','2017-09-10','Manhattan');
INSERT INTO races (name, race_date, location) VALUES ('TCS New York City Marathon Tune-Up (18M)','2017-09-17','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('New Balance Bronx 10 Mile','2017-09-24','Bronx');
INSERT INTO races (name, race_date, location) VALUES ('Gretes Great Gallop','2017-10-01','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Staten Island Half','2017-10-08','Staten Island');
INSERT INTO races (name, race_date, location) VALUES ('Ragnar Trail Wawayanda Lake','2017-10-13','New Jersey');
INSERT INTO races (name, race_date, location) VALUES ('Poland Spring Marathon Kickoff (5M)','2017-10-29','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Abbott Dash to the Finish Line 5K','2017-11-04','Manhattan');
INSERT INTO races (name, race_date, location) VALUES ('TCS New York City Marathon','2017-11-05','Five Boroughs');
INSERT INTO races (name, race_date, location) VALUES ('NYRR NYC 60K','2017-11-18','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Race to Deliver 4M To Benefit Gods Love We Deliver','2017-11-19','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Jingle Bell Jog','2017-12-02','Prospect Park Bandshell');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Ted Corbitt 15K','2017-12-09','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('NYRR Midnight Run','2017-12-31','Central Park');
INSERT INTO races (name, race_date, location) VALUES ('Bank of America Chicago Marathon','2017-10-08','Chicago');
INSERT INTO races (name, race_date, location) VALUES ('Tokyo Marathon 2017','2017-02-26','Tokyo');
INSERT INTO races (name, race_date, location) VALUES ('Boston Marathon','2017-04-17','Boston');
INSERT INTO races (name, race_date, location) VALUES ('Virgin Money London Marathon','2017-04-23','London');
INSERT INTO races (name, race_date, location) VALUES ('Berlin Marathon','2017-09-23','Berlin');

COMMIT;
